options:
  server_url: http://localhost:8080/opencga
api:
  Users:
    ignore: False
    key: User
    extended: True
    shortcuts:
      user: u
      password: p
      study: s
    commands:
      login:
        ignore: False
        extended: True
  Projects:
    ignore: False
    key: Project
    shortcuts:
      study: s
  Studies:
    ignore: False
    key: Study
  Files:
    ignore: False
    key: File
    shortcuts:
      study: s
  Jobs:
    ignore: False
    key: Job
    shortcuts:
      study: s
  Samples:
    ignore: False
    key: Sample
    shortcuts:
      study: s
  Individuals:
    ignore: False
    key: Individual
    shortcuts:
      study: s
  Families:
    ignore: False
    key: Family
  Cohorts:
    ignore: False
    key: Cohort
    shortcuts:
      study: s
  Disease Panels:
    ignore: False
    key: DiseasePanel
    shortcuts:
      study: s
  Analysis - Alignment:
    ignore: False
    key: Alignment
    shortcuts:
      study: s
  Analysis - Variant:
    ignore: False
    key: Variant
    shortcuts:
      study: s
  Analysis - Clinical:
    ignore: False
    key: ClinicalAnalysis
    shortcuts:
      study: s
  Operations - Variant Storage:
    ignore: False
    key: VariantOperation
    shortcuts:
      study: s
  Meta:
    ignore: False
    key: Meta
    shortcuts:
      study: s
  GA4GH:
    ignore: False
    key: GA4GH
    shortcuts:
      study: s
  Admin:
    ignore: False
    key: Admin
    shortcuts:
      study: s
