options:
  server_url: http://localhost:8080/opencga
  version: 1.0
  cli_output_dir: opencga-client/src/main/java/org/opencb/opencga/client/rest/clients
  options_output_dir: ../../../../src/main/java/org/opencb/opencga/app/cli/main/options
  executors_output_dir: ../../../../src/main/java/org/opencb/opencga/app/cli/main/executors/catalog
  executors_package: org.opencb.opencga.app.cli.main.executors.catalog
  options_package: org.opencb.opencga.app.cli.main.options
  parser_package: org.opencb.opencga.app.cli.main
  ignore_types:
    - string
    - object
    - integer
    - int
    - map
    - boolean
    - enum
    - long
    - java.lang.String
    - java.lang.Boolean
    - java.lang.Integer
    - java.lang.Long
    - java.lang.Short
    - java.lang.Double
    - java.lang.Float
    - java.lang.
api:
  Users:
    ignore: False
    key: User
  Projects:
    ignore: False
    key: Project
  Studies:
    ignore: False
    key: Study
  Files:
    ignore: False
    key: File
    commands:
      upload:
        ignore: True
        subcommands:
          hash:
            ignore: True
          serialVersionUID:
            ignore: True
  Jobs:
    ignore: False
    key: Job
  Samples:
    ignore: False
    key: Sample
  Individuals:
    ignore: False
    key: Individual
  Families:
    ignore: False
    key: Family
  Cohorts:
    ignore: False
    key: Cohort
  Disease Panels:
    ignore: False
    key: DiseasePanel
  Analysis - Alignment:
    ignore: False
    key: Alignment
  Analysis - Variant:
    ignore: False
    key: Variant
  Analysis - Clinical:
    ignore: False
    key: Clinical
  Operations - Variant Storage:
    ignore: False
    key: VariantOperation
  Meta:
    ignore: False
    key: Meta
  GA4GH:
    ignore: True
    key: GA4GH
  Admin:
    ignore: True
    key: Admin
