options:
  outputDir: opencga-app/src/main/java/org/opencb/opencga/app/cli/main/
  ignoreTypes:
    - string
    - object
    - integer
    - int
    - map
    - boolean
    - enum
    - long
    - java.lang.String
    - java.lang.Boolean
    - java.lang.Integer
    - java.lang.Long
    - java.lang.Short
    - java.lang.Double
    - java.lang.Float
    - java.lang.
apiConfig:
  shortcuts:
    - name: user
      shortcut: u
    - name: study
      shortcut: s
    - name: exclude
      shortcut: E
    - name: include
      shortcut: I
    - name: project
      shortcut: p
    - name: creationDate
      shortcut: cd
    - name: modificationDate
      shortcut: md
  categoryConfigList:
    - name: users
      ignore: False
      key: User
      extended: True
      commands:
        - name: update-filters
          ignore: True
        - name: login
          extended: True
    - name: projects
      ignore: False
      key: Project
    - name: studies
      ignore: False
      key: Study
    - name: files
      ignore: False
      key: File
      commands:
        - name: upload
          ignore: True
          subcommands:
            - name: hash
              ignore: True
            - name: serialVersionUID
              ignore: True
    - name: jobs
      ignore: False
      key: Job
    - name: samples
      ignore: False
      key: Sample
    - name: individuals
      ignore: False
      key: Individual
    - name: families
      ignore: False
      key: Family
    - name: cohorts
      ignore: False
      key: Cohort
    - name: panels
      commandName: panels
      ignore: False
      key: DiseasePanel
    - name: analysisAlignment
      commandName: alignments
      ignore: False
      key: Alignment
      analysis: True
    - name: analysisVariant
      commandName: variant
      ignore: False
      key: Variant
      analysis: True
    - name: analysisClinical
      commandName: clinical
      ignore: False
      key: ClinicalAnalysis
      analysis: True
    - name: operation
      commandName: operations
      ignore: False
      key: VariantOperation
      operations: True
    - name: meta
      ignore: False
      key: Meta
    - name: ga4gh
      ignore: True
      key: GA4GH
    - name: admin
      ignore: True
      key: Admin
