options:
  serverUrl: http://localhost:8080/opencga
  version: 1.0
  parserOutputDir: opencga-client/src/main/java/org/opencb/opencga/client/rest/clients
  #optionsOutputDir: ../../../../src/main/java/org/opencb/opencga/app/cli/main/options
  optionsOutputDir: opencga-app/src/main/java/org/opencb/opencga/app/cli/main/options
  #executorsOutputDir: ../../../../src/main/java/org/opencb/opencga/app/cli/main/executors
  executorsOutputDir: opencga-app/src/main/java/org/opencb/opencga/app/cli/main/executors
  executorsPackage: org.opencb.opencga.app.cli.main.executors
  optionsPackage: org.opencb.opencga.app.cli.main.options
  parserPackage: org.opencb.opencga.app.cli.main
  ignoreTypes:
    - string
    - object
    - integer
    - int
    - map
    - boolean
    - enum
    - long
    - java.lang.String
    - java.lang.Boolean
    - java.lang.Integer
    - java.lang.Long
    - java.lang.Short
    - java.lang.Double
    - java.lang.Float
    - java.lang.
apiConfig:
  categoryConfigList:
    - name: users
      ignore: False
      key: User
      extended: True
      shortcuts:
        - name: user
          shortcut: u
        - name: password
          shortcut: p
        - name: study
          shortcut: s
      commands:
        - name: update-filters
          ignore: True
        - name: login
          extended: True
    - name: projects
      ignore: False
      key: Project
      shortcuts:
        - name: study
          shortcut: s
    - name: studies
      ignore: False
      key: Study
    - name: files
      ignore: False
      key: File
      commands:
        - name: upload
          ignore: True
          subcommands:
            - name: hash
              ignore: True
            - name: serialVersionUID
              ignore: True
      shortcuts:
        - name: study
          shortcut: s
    - name: jobs
      ignore: False
      key: Job
      shortcuts:
        - name: study
          shortcut: s
    - name: samples
      ignore: False
      key: Sample
      shortcuts:
        - name: study
          shortcut: s
    - name: individuals
      ignore: False
      key: Individual
      shortcuts:
        - name: study
          shortcut: s
    - name: families
      ignore: False
      key: Family
    - name: cohorts
      ignore: False
      key: Cohort
      shortcuts:
        - name: study
          shortcut: s
    - name: panels
      commandName: panels
      ignore: False
      key: DiseasePanel
      shortcuts:
        - name: study
          shortcut: s
    - name: analysisAlignment
      commandName: alignments
      ignore: False
      key: Alignment
      shortcuts:
        - name: study
          shortcut: s
      analysis: True
    - name: analysisVariant
      commandName: variant
      ignore: False
      key: Variant
      shortcuts:
        - name: study
          shortcut: s
      analysis: True
    - name: analysisClinical
      commandName: clinical
      ignore: False
      key: ClinicalAnalysis
      shortcuts:
        - name: study
          shortcut: s
      analysis: True
    - name: operation
      commandName: operations
      ignore: False
      key: VariantOperation
      shortcuts:
        - name: study
          shortcut: s
      operations: True
    - name: meta
      ignore: False
      key: Meta
      shortcuts:
        - name: study
          shortcut: s
    - name: ga4gh
      ignore: True
      key: GA4GH
      shortcuts:
        - name: study
          shortcut: s
    - name: admin
      ignore: True
      key: Admin
      shortcuts:
        - name: study
          shortcut: s