options:
  serverUrl: http://localhost:8080/opencga
  version: 1.0
  parserOutputDir: opencga-client/src/main/java/org/opencb/opencga/client/rest/clients
  optionsOutputDir: ../../../../src/main/java/org/opencb/opencga/app/cli/main/options
  executorsOutputDir: ../../../../src/main/java/org/opencb/opencga/app/cli/main/executors
  executorsPackage: org.opencb.opencga.app.cli.main.executors
  optionsPackage: org.opencb.opencga.app.cli.main.options
  parserPackage: org.opencb.opencga.app.cli.main
  ignoreTypes:
    - string
    - object
    - integer
    - int
    - map
    - boolean
    - enum
    - long
    - java.lang.String
    - java.lang.Boolean
    - java.lang.Integer
    - java.lang.Long
    - java.lang.Short
    - java.lang.Double
    - java.lang.Float
    - java.lang.
ApiConfig:
  Users:
    ignore: False
    key: User
    extended: True
    shortcuts:
      user: u
      password: p
      study: s
    commands:
      login:
        extended: True
  Projects:
    ignore: False
    key: Project
    shortcuts:
      study: s
  Studies:
    ignore: False
    key: Study
  Files:
    ignore: False
    key: File
    commands:
      upload:
        ignore: True
        subcommands:
          hash:
            ignore: True
          serialVersionUID:
            ignore: True
    shortcuts:
      study: s
  Jobs:
    ignore: False
    key: Job
    shortcuts:
      study: s
  Samples:
    ignore: False
    key: Sample
    shortcuts:
      study: s
  Individuals:
    ignore: False
    key: Individual
    shortcuts:
      study: s
  Families:
    ignore: False
    key: Family
  Cohorts:
    ignore: False
    key: Cohort
    shortcuts:
      study: s
  Disease Panels:
    command_name: panels
    ignore: False
    key: DiseasePanel
    shortcuts:
      study: s
  Analysis - Alignment:
    command_name: alignments
    ignore: False
    key: Alignment
    shortcuts:
      study: s
    analysis: True
  Analysis - Variant:
    command_name: variant
    ignore: False
    key: Variant
    shortcuts:
      study: s
    analysis: True
  Analysis - Clinical:
    command_name: clinical
    ignore: False
    key: ClinicalAnalysis
    shortcuts:
      study: s
    analysis: True
  Operations - Variant Storage:
    command_name: operations
    ignore: False
    key: VariantOperation
    shortcuts:
      study: s
    operations: True
  Meta:
    ignore: False
    key: Meta
    shortcuts:
      study: s
  GA4GH:
    ignore: True
    key: GA4GH
    shortcuts:
      study: s
  Admin:
    ignore: True
    key: Admin
    shortcuts:
      study: s