# Default values for opencga.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploySolr: false
deployMongo: false

catalog:
  database:
    hosts: "FILL_ME"
    user: "FILL_ME"
    password: "FILL_ME"

cellbase:
  host: "FILL_ME"

analysis:
  index:
    variant:
      maxConcurrentJobs: 100
  execution:
    id: "k8s"
    options:
      k8s:
        masterNode: "FILL_ME"
        namespace: "FILL_ME"

solr:
  hosts: "FILL_ME"

hadoop:
  sshDns: "FILL_ME"
  sshUsername: "FILL_ME"
  sshPassword: "FILL_ME"

opencga:
  secretsName: "opencga-secrets"
  admin:
    password: "FILL_ME"

# https://docs.microsoft.com/en-gb/azure/aks/azure-files-volume
azureStorageAccount:
  enabled: true
  name: "FILL_ME"
  key: "FILL_ME"

clusterRoleBinding:
  name: fabric8-rbac

blobfuse:
  enabled: false

defaultConf:
  name: "default-conf"

volumes:
  conf:
    shareName: conf
  analysisconf:
    shareName: analysisconf
  sessions:
    shareName: sessions
  variants:
    shareName: variants

rest:
  name: rest
  replicaCount: 3

  image:
    # TODO: Currently building from dev image. Update once release available.
    repository: opencb/opencga-base:2.0.0-dev-hdp3.1
    pullPolicy: Always

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name:

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    #type: LoadBalancer
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      # nginx.ingress.kubernetes.io/rewrite-target: /$1
      # kubernetes.io/tls-acme: "true"
    host: "opencga.local" # This host name should be added to the internal DNS zone pointing to the nginx service external IP
    paths:
    - /opencga/
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: 
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector: 
    agentpool: default
    beta.kubernetes.io/os: linux
    kubernetes.io/role: agent

  tolerations: []

  affinity: {}

# TODO
grpc:
  name: grpc

master:
  name: master
  replicaCount: 1

  image:
    # TODO: Currently building from dev image. Update once release available.
    repository: opencb/opencga-base:2.0.0-dev-hdp3.1
    pullPolicy: Always

  imagePullSecrets: []


  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name:

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources: 
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 512Mi

  nodeSelector: 
    agentpool: default
    beta.kubernetes.io/os: linux
    kubernetes.io/role: agent


  tolerations: []

  affinity: {}

init:
  name: init
  image:
    # TODO: Currently building from dev image. Update once release available.
    repository: opencb/opencga-init:2.0.0-dev-hdp3.1
    pullPolicy: Always

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
  # runAsUser: 1000

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}
