version: "3.3"

services:
  mongodb:
    image: mongo:4.2.18
    volumes:
      - ~/opencga-docker-data/mongodb:/data/mongodb
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs0", "--bind_ip_all", "--dbpath", "/data/mongodb" ]

  solr:
    image: solr:8.8.2
    volumes:
      - ~/opencga-docker-data/solr:/var/solr/data
    environment:
      - SOLR_USER=imedina
      - SOLR_UID=1000

  init:
    image: opencb/opencga-base:2.3.0-SNAPSHOT
    depends_on:
      - mongodb
      - solr
    volumes:
      - ./init.sh:/opt/opencga/bin/init.sh
      - ./conf/:/opt/opencga/conf/
      - ./mongodb-replica-set-init.js:/opt/mongodb/mongodb-replica-set-init.js
    command: [ "/opt/opencga/bin/init.sh" ]

  rest:
    image: opencb/opencga-base:2.3.0-SNAPSHOT
    depends_on:
      - init
    ports:
      - "9090:9090"
    volumes:
      - ./rest.sh:/opt/opencga/bin/rest.sh
      - ./conf/:/opt/opencga/conf/
    command: [ "/opt/opencga/bin/rest.sh" ]

#  hbase:
#    image: dajobe/hbase