version: "3.3"

services:
  mongodb:
    image: mongo:4.2.18
    ports:
      - "27017:27017"
#    expose:
#      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs0", "--bind_ip_all" ]
#    environment:
#       MONGO_INITDB_ROOT_USERNAME: opencga
#       MONGO_INITDB_ROOT_PASSWORD: opencga

  solr:
    image: solr:8.8.2
  #    environment:
  #      MYSQL_PASSWORD: wordpress

  init:
    image: opencb/opencga-base:2.3.0-SNAPSHOT
    depends_on:
      - mongodb
      - solr
    volumes:
      - ./init.sh:/opt/opencga/bin/init.sh
      - ./conf/:/opt/opencga/conf/
      - ./mongodb-replica-set-init.js:/opt/mongodb/mongodb-replica-set-init.js
    command: [ "/opt/opencga/bin/init.sh" ]

  rest:
    image: opencb/opencga-base:2.3.0-SNAPSHOT
    depends_on:
      - init
    ports:
      - "9090:9090"
    volumes:
      - ./rest.sh:/opt/opencga/bin/rest.sh
      - ./conf/:/opt/opencga/conf/
    command: [ "/opt/opencga/bin/rest.sh" ]


      # command: [ "/opt/opencga/bin/opencga-admin.sh", "server", "rest", "--start", "--port", "9090" ]
      #    environment:
      #      WORDPRESS_DB_HOST: db

      #  master:
    #    image: opencga-base:2.3.0-SNAPSHOT
    #    depends_on:
    #      - rest
    #    volumes:
    #      - wordpress_data:/var/www/html
    #    environment:
    #      WORDPRESS_DB_HOST: db

volumes:
  db_data: { }
  wordpress_data: { }