apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clusterRoleBinding.name" . | quote}}
subjects:
 - kind: ServiceAccount
   name: {{ .Values.master.name }}
   namespace: {{ .Release.Namespace }}
roleRef:
 kind: ClusterRole
 name: cluster-admin
 apiGroup: rbac.authorization.k8s.io
