apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.opencga.secretsName }}
type: "Opaque"
data:
  openCgaAdminPassword: {{ .Values.opencga.admin.password | b64enc | quote }}
  hdInsightSshPassword: {{ .Values.hadoop.sshPassword | b64enc | quote }}
  mongoDbPassword: {{ .Values.catalog.database.password | b64enc | quote }}
