---
logLevel: "INFO"

# Number of seconds that session remains open without any activity [10 min]
#cliSessionDuration: 600

## REST client configuration options
rest:
  hosts:
    - name: "opencga"
      url: "${OPENCGA.CLIENT.REST.HOST}"
    - name: "opencga-demo"
      url: "http://localhost:9090/opencga"
    - name: "opencga-demo1"
      url: "http://localhost:9191/opencga"
  defaultHostIndex: 0
  tokenAutoRefresh: true
  tlsAllowInvalidCertificates: false
  query:
    batchSize: 200
    limit: 2000


## gRPC configuration options
grpc:
  host: "${OPENCGA.CLIENT.GRPC.HOST}"
