---
logLevel: "INFO"

# Number of seconds that session remains open without any activity [10 min]
cliSessionDuration: 600

## REST client configuration options
rest:
  hostname: "opencga"
  url: "${OPENCGA.CLIENT.REST.HOST}"
  hosts:
    - name: "opencga-demo"
      url: "http://localhost:9090/opencga"
    - name: "opencga-demo1"
      url: "http://localhost:9191/opencga"
  tokenAutoRefresh: true
  tlsAllowInvalidCertificates: false
  timeout: 90000
  query:
    batchSize: 200
    limit: 2000


## gRPC configuration options
grpc:
  host: "${OPENCGA.CLIENT.GRPC.HOST}"


## Configure the default behaviour when query variants
variant:
  unknownGenotype: "0/0"
